force-app/main/default/objects/BatalhasContato__c/BatalhasContato__c.object-meta.xml
<CustomObject>
    <description>objeto de junção com as batalhas</description>
    <label>Batalhas Contato</label>
    <nameField>
        <displayFormat>Skill-{000000000}</displayFormat>
        <label>Batalhas do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas Contatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhasContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relacionamento com o contato</description>
    <inlineHelpText>relacionamento com o contato</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas Contatos</relationshipLabel>
    <relationshipName>BatalhasContatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BatalhasContatoHandler.cls
public  class BatalhasContatoHandler {
    
    public void contaBatalhaInsert(List<BatalhasContato__c> listaBatalha){       
     BatalhasContatoTriggerHelper.totalizaBatalhasEmAndmento(listaBatalha);                        
    }  
    
    public void contaBatalhaDelete(List<BatalhasContato__c> listaBatalha){
      BatalhasContatoTriggerHelper.totalizaBatalhasEmAndmento(listaBatalha);                       
    }   
    
    public void contatoBatalhaUpdate(List<BatalhasContato__c> listaBatalha, Map<id,BatalhasContato__c> mapOld ){      
        list<BatalhasContato__c> batalhasContatos = new list<BatalhasContato__c>();
                
        for(BatalhasContato__c batalhasContato : listaBatalha ){
            
            if ( mapOld.get(batalhasContato.id).Contato__c != batalhasContato.contato__c  ) {               
                batalhasContatos.add(mapOld.get(batalhasContato.id));
                batalhasContatos.add(batalhasContato);             
            }                       
        }
        
        BatalhasContatoTriggerHelper.totalizaBatalhasEmAndmento(batalhasContatos);  
                
    }

          
   
}