force-app/main/default/objects/BatalhasContato__c/BatalhasContato__c.object-meta.xml
<CustomObject>
    <description>objeto de junção com as batalhas</description>
    <label>Batalhas Contato</label>
    <nameField>
        <displayFormat>Skill-{000000000}</displayFormat>
        <label>Batalhas do Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batalhas Contatos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/BatalhasContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relacionamento com o contato</description>
    <inlineHelpText>relacionamento com o contato</inlineHelpText>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Batalhas Contatos</relationshipLabel>
    <relationshipName>BatalhasContatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumeroBatalhas__c.field-meta.xml
<CustomField>
    <fullName>NumeroBatalhas__c</fullName>
    <description>exibe o numero de 
batalhas em que o contato esta participando</description>
    <inlineHelpText>exibe o numero de 
batalhas em que o contato esta participando</inlineHelpText>
    <label>Numero Batalhas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BatalhasContatoTriggerHelper.cls
public class BatalhasContatoTriggerHelper {
    
    public static void totalizaBatalhasEmAndmento(List<BatalhasContato__c> listaBatalha){
        //declarando variaveis 
        List<Contact> contactToUpdate = new List<Contact>();
        Set<id> contactIds = new Set<id>();
        
        //agrupar os id
        for(BatalhasContato__c Lista : listaBatalha){
            contactIds.add(Lista.Contato__c);
        }
        

        for(AggregateResult a : [select Count(id)total,Contato__c  from BatalhasContato__c  where Contato__c in :contactIds group by Contato__c ]  ) {   

          Contact contato = new Contact();
          contato.Id = String.valueOf( a.get('Contato__c'));
          contato.NumeroBatalhas__c =  Integer.valueOf(a.get('total'));   
          contactToUpdate.add(contato);  
      }
        if (! contactToUpdate.isEmpty() ) {
            update contactToUpdate;
        }     
         
            
    }
}