force-app/main/default/objects/Contact/fields/Nomedeguerra__c.field-meta.xml
<CustomField>
    <fullName>Nomedeguerra__c</fullName>
    <description>Nome de guerra do herói</description>
    <inlineHelpText>Nome de guerra do herói</inlineHelpText>
    <label>Nome de guerra</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Planeta__c.field-meta.xml
<CustomField>
    <fullName>Planeta__c</fullName>
    <description>Digite de qual planeta você veio</description>
    <inlineHelpText>Seu Planeta Natal</inlineHelpText>
    <label>Planeta</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <label>Heroi</label>
</RecordType>

force-app/main/default/classes/FormularioHeroisCMPController.cls
public with sharing class FormularioHeroisCMPController {

    @AuraEnabled
    public static String salvarHerois( string jsonHero){       
       System.debug('meu jsonHero ::' + jsonHero);  
        
        try{
            Heroi heroi = (Heroi) JSON.deserialize(jsonHero, heroi.class);
            Contact contato = new Contact();          
            contato.FirstName       = heroi.firstname;
            contato.LastName        = heroi.lastname;
            contato.Nomedeguerra__c = heroi.Nomedeguerra;
            contato.Planeta__c      = heroi.planeta;
            contato.Description     = heroi.descricao;
            
            insert contato;

              
          return 'Heroi Criado com Sucesso'; 
            
        }catch(Exception e ){
           System.debug('Error ::' + e.getMessage());  
           return 'ops..' + e.getMessage();  
        }        
    }
    
    public class Heroi{
      public string firstname;
      public string lastname;
      public string Nomedeguerra;
      public string planeta;
      public string descricao;
        
    }
    
}